# Exercise Session 1
## NumPy Arrays vs TensorFlow2 Tensors

### Import Libraries

In [1]:
import tensorflow as tf
import numpy as np
import os
import random
print('TensorFlow2 vesion:',tf.__version__)

TensorFlow2 vesion: 2.6.0


### Set seed for reproducibility

In [2]:
# Random seed for reproducibility
seed = 42

random.seed(seed)
os.environ['PYTHONHASHSEED'] = str(seed)
np.random.seed(seed)
tf.random.set_seed(seed)
tf.compat.v1.set_random_seed(seed)

### NumPy 

1-dimentional NumPy array

In [3]:
# Define a list 
list1d = [0,1,2,3,4]
shape1d = len(list1d)

# Create a NumPy array from a list
array1d = np.array(list1d, dtype=np.int32)
print("Dimensions:",array1d.ndim)
print("Type:",array1d.dtype)
print("Shape:", array1d.shape)
print(array1d)

Dimensions: 1
Type: int32
Shape: (5,)
[0 1 2 3 4]


In [4]:
# Define a function to inspect NumPy arrays
def describe_array(np_array):
    print("Dimensions:",np_array.ndim)
    print("Type:",np_array.dtype)
    print("Shape:",np_array.shape)
    print(np_array,"\n")

In [5]:
# Create a NumPy array of zeros
array1d = np.zeros(shape=(shape1d,), dtype=np.int32)
describe_array(array1d)

Dimensions: 1
Type: int32
Shape: (5,)
[0 0 0 0 0] 



In [6]:
# Create a NumPy array of twos
array1d = np.ones(shape=(shape1d,), dtype=np.float32) * 2
describe_array(array1d)

Dimensions: 1
Type: float32
Shape: (5,)
[2. 2. 2. 2. 2.] 



In [7]:
# Create a NumPy array of ordered integers
array1d = np.arange(start=0, stop=10, step=2, dtype=np.int32)
describe_array(array1d)

Dimensions: 1
Type: int32
Shape: (5,)
[0 2 4 6 8] 



In [8]:
# Create a NumPy array from a uniform distribution
# array1d = np.random.rand(shape1d,)
# describe_array(array1d)

In [9]:
# Create a NumPy array from a normal distribution
array1d = np.random.randn(shape1d,)
describe_array(array1d)

Dimensions: 1
Type: float64
Shape: (5,)
[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337] 



2-dimentional NumPy array

In [10]:
# Create a 2-dimentional NumPy array
array2d = np.array([[0,1,2,3,4],[5,6,7,8,9]], dtype=np.int32)
orininal_shape2d = array2d.shape
describe_array(array2d)

Dimensions: 2
Type: int32
Shape: (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]] 



In [11]:
# Reshape a 2-dimentional NumPy array
array2d = np.reshape(array2d, (orininal_shape2d[1],orininal_shape2d[0]))
describe_array(array2d)

Dimensions: 2
Type: int32
Shape: (5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 



In [12]:
# Reshape a 2-dimentional NumPy array
array2d = np.reshape(array2d, (orininal_shape2d[0]*orininal_shape2d[1]))
describe_array(array2d)

Dimensions: 1
Type: int32
Shape: (10,)
[0 1 2 3 4 5 6 7 8 9] 



n-dimentional NumPy array

In [13]:
# Create a n-dimentional NumPy array
arraynd = np.random.rand(3,4,5)
describe_array(arraynd)

Dimensions: 3
Type: float64
Shape: (3, 4, 5)
[[[0.05808361 0.86617615 0.60111501 0.70807258 0.02058449]
  [0.96990985 0.83244264 0.21233911 0.18182497 0.18340451]
  [0.30424224 0.52475643 0.43194502 0.29122914 0.61185289]
  [0.13949386 0.29214465 0.36636184 0.45606998 0.78517596]]

 [[0.19967378 0.51423444 0.59241457 0.04645041 0.60754485]
  [0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]
  [0.30461377 0.09767211 0.68423303 0.44015249 0.12203823]
  [0.49517691 0.03438852 0.9093204  0.25877998 0.66252228]]

 [[0.31171108 0.52006802 0.54671028 0.18485446 0.96958463]
  [0.77513282 0.93949894 0.89482735 0.59789998 0.92187424]
  [0.0884925  0.19598286 0.04522729 0.32533033 0.38867729]
  [0.27134903 0.82873751 0.35675333 0.28093451 0.54269608]]] 



In [14]:
# Flatten a n-dimentional NumPy array
arraynd = arraynd.flatten()
arraynd

array([0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
       0.96990985, 0.83244264, 0.21233911, 0.18182497, 0.18340451,
       0.30424224, 0.52475643, 0.43194502, 0.29122914, 0.61185289,
       0.13949386, 0.29214465, 0.36636184, 0.45606998, 0.78517596,
       0.19967378, 0.51423444, 0.59241457, 0.04645041, 0.60754485,
       0.17052412, 0.06505159, 0.94888554, 0.96563203, 0.80839735,
       0.30461377, 0.09767211, 0.68423303, 0.44015249, 0.12203823,
       0.49517691, 0.03438852, 0.9093204 , 0.25877998, 0.66252228,
       0.31171108, 0.52006802, 0.54671028, 0.18485446, 0.96958463,
       0.77513282, 0.93949894, 0.89482735, 0.59789998, 0.92187424,
       0.0884925 , 0.19598286, 0.04522729, 0.32533033, 0.38867729,
       0.27134903, 0.82873751, 0.35675333, 0.28093451, 0.54269608])

In [15]:
# Concatenate two NumPy arrays
array1 = np.ones((1,3,2))
array2 = np.zeros((1,3,2))

array_c1 = np.concatenate((array1,array2), axis=0)
describe_array(array_c1)

array_c2 = np.concatenate((array1,array2), axis=1)
describe_array(array_c2)

array_c3 = np.concatenate((array1,array2), axis=2)
describe_array(array_c3)

Dimensions: 3
Type: float64
Shape: (2, 3, 2)
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]] 

Dimensions: 3
Type: float64
Shape: (1, 6, 2)
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]] 

Dimensions: 3
Type: float64
Shape: (1, 3, 4)
[[[1. 1. 0. 0.]
  [1. 1. 0. 0.]
  [1. 1. 0. 0.]]] 



## Tensorflow

TensorFlow constant

In [16]:
# Define a scalar Tensor
rank0_tensor = tf.constant(42)
print("Dimensions:",rank0_tensor.ndim)
print("Type:",rank0_tensor.dtype)
print("Shape:",rank0_tensor.shape)
print("Device",rank0_tensor.device)
print(rank0_tensor,"\n")

Dimensions: 0
Type: <dtype: 'int32'>
Shape: ()
Device /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(42, shape=(), dtype=int32) 



In [17]:
# Define a function to inspect Tensors
def describe_tensor(tensor, device=False):
    print("Dimensions:",tensor.ndim)
    print("Type:",tensor.dtype)
    print("Shape:",tensor.shape)
    if(device):
        print("Device",tensor.device)
    print(tensor,"\n")

In [18]:
# Define a vector Tensor
#rank1_tensor = tf.constant([-1.,0.,1.])
#describe_tensor(rank1_tensor, True)

In [19]:
# Define a matrix Tensor
rank2_tensor = tf.constant([[-1,1],[-2,2],[-3,3]])
describe_tensor(rank2_tensor, True)

Dimensions: 2
Type: <dtype: 'int32'>
Shape: (3, 2)
Device /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[-1  1]
 [-2  2]
 [-3  3]], shape=(3, 2), dtype=int32) 



In [20]:
# Tensors can have an arbitrary number of axes
rank3_tensor = tf.constant([[[0,0.1,0.2,0.3],[0.4,0.5,0.6,0.7]],[[0,1,2,3],[4,5,6,7]],[[0,10,20,30],[40,50,60,70]]])
describe_tensor(rank3_tensor)

Dimensions: 3
Type: <dtype: 'float32'>
Shape: (3, 2, 4)
tf.Tensor(
[[[ 0.   0.1  0.2  0.3]
  [ 0.4  0.5  0.6  0.7]]

 [[ 0.   1.   2.   3. ]
  [ 4.   5.   6.   7. ]]

 [[ 0.  10.  20.  30. ]
  [40.  50.  60.  70. ]]], shape=(3, 2, 4), dtype=float32) 



NumPy conversion

In [21]:
# Convert NumPy array to Tensor
array = np.array([0,1,2,3,4])
tensor = tf.convert_to_tensor(array)
describe_tensor(tensor)

Dimensions: 1
Type: <dtype: 'int64'>
Shape: (5,)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64) 



In [22]:
# Convert Tensor to NumPy array
tensor = tf.constant([0,1,2,3,4])
array = np.array(tensor)
describe_array(array)

Dimensions: 1
Type: int32
Shape: (5,)
[0 1 2 3 4] 



Structured Tensors

In [23]:
# Create a Tensor of zeros
t_zeros = tf.zeros(shape=(4, 4), dtype=tf.int32)
describe_tensor(t_zeros)

Dimensions: 2
Type: <dtype: 'int32'>
Shape: (4, 4)
tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32) 



In [24]:
# Create a Tensor of 9s
#t_nines = tf.zeros(shape=(4, 4), dtype=tf.int32) + 9
#describe_tensor(t_nines)

In [25]:
# Create a Tensor of 9s
t_nines = tf.ones(shape=(4, 4), dtype=tf.int32) * 9
describe_tensor(t_nines)

Dimensions: 2
Type: <dtype: 'int32'>
Shape: (4, 4)
tf.Tensor(
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]], shape=(4, 4), dtype=int32) 



In [26]:
# Create a normal Tensor
t_normal = tf.random.normal(shape=(2, 4, 4))
describe_tensor(t_normal)

Dimensions: 3
Type: <dtype: 'float32'>
Shape: (2, 4, 4)
tf.Tensor(
[[[ 0.3274685  -0.8426258   0.3194337  -1.4075519 ]
  [-2.3880599  -1.0392479  -0.5573232   0.539707  ]
  [ 1.6994323   0.28893656 -1.5066116  -0.26454744]
  [-0.59722406 -1.9171132  -0.62044144  0.8504023 ]]

 [[-0.40604794 -3.0258412   0.9058464   0.29855987]
  [-0.22561555 -0.7616443  -1.891714   -0.9384712 ]
  [ 0.77852213 -0.47338897  0.97772694  0.24694404]
  [ 0.20573747 -0.5256233   0.32410017  0.02545409]]], shape=(2, 4, 4), dtype=float32) 



Reshape, Squeeze and Slice

In [27]:
# Expand and reduce dimensionalities of a Tensor
tensor2d = tf.constant(5, shape=(4,5))
describe_tensor(tensor2d)

tensor3d = tf.expand_dims(tensor2d, axis=-1)
describe_tensor(tensor3d)

tensor2d = tf.squeeze(tensor3d, axis=-1)
describe_tensor(tensor2d)

Dimensions: 2
Type: <dtype: 'int32'>
Shape: (4, 5)
tf.Tensor(
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]], shape=(4, 5), dtype=int32) 

Dimensions: 3
Type: <dtype: 'int32'>
Shape: (4, 5, 1)
tf.Tensor(
[[[5]
  [5]
  [5]
  [5]
  [5]]

 [[5]
  [5]
  [5]
  [5]
  [5]]

 [[5]
  [5]
  [5]
  [5]
  [5]]

 [[5]
  [5]
  [5]
  [5]
  [5]]], shape=(4, 5, 1), dtype=int32) 

Dimensions: 2
Type: <dtype: 'int32'>
Shape: (4, 5)
tf.Tensor(
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]], shape=(4, 5), dtype=int32) 



In [28]:
# Reshape the form of a Tensor
tensor1d = tf.range(9)
describe_tensor(tensor1d)

tensor2d = tf.reshape(tensor1d, shape=(3,3))
describe_tensor(tensor2d)

flattened = tf.reshape(tensor2d, shape=(-1))
describe_tensor(flattened)


Dimensions: 1
Type: <dtype: 'int32'>
Shape: (9,)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32) 

Dimensions: 2
Type: <dtype: 'int32'>
Shape: (3, 3)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32) 

Dimensions: 1
Type: <dtype: 'int32'>
Shape: (9,)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32) 



In [29]:
# Apply slicing operations on Tensors
tensor2d = tf.reshape(tf.range(16), shape=(4,4))
describe_tensor(tensor2d)
print('Single Tensor element, position[1,2]:',tensor2d[1,2])
#print('\nSingle Tensor element, position[-1,2]:',tensor2d[-1,2])
#print('\nTensor slice, portion[1:3:1, 2:4:1]:',tensor2d[1:3:1, 2:4:1])
print('\nTensor slice, portion[1:3, 2:4]:',tensor2d[1:3, 2:4])
print('\nTensor slice, portion[1:, 2:]:',tensor2d[1:, 2:])
print('\nTensor slice, from[1,1] to[3, 2]:',tf.slice(tensor2d,[1,1],[3,2]))

Dimensions: 2
Type: <dtype: 'int32'>
Shape: (4, 4)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int32) 

Single Tensor element, position[1,2]: tf.Tensor(6, shape=(), dtype=int32)

Tensor slice, portion[1:3, 2:4]: tf.Tensor(
[[ 6  7]
 [10 11]], shape=(2, 2), dtype=int32)

Tensor slice, portion[1:, 2:]: tf.Tensor(
[[ 6  7]
 [10 11]
 [14 15]], shape=(3, 2), dtype=int32)

Tensor slice, from[1,1] to[3, 2]: tf.Tensor(
[[ 5  6]
 [ 9 10]
 [13 14]], shape=(3, 2), dtype=int32)


In [30]:
# Apply condition to Tensors
indices = tf.where(tensor2d % 2 == 0)
print(tf.gather_nd(tensor2d, indices))

tf.Tensor([ 0  2  4  6  8 10 12 14], shape=(8,), dtype=int32)
